# Generated by Django 4.2.6 on 2023-10-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('profile_picture', models.ImageField(upload_to='profile/images')),
                ('created_at', models.DateField(auto_now=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
